<!DOCTYPE html>
<html lang="zh-cn">
<head>
<script>var sitePath='seacms6.54/'</script>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="renderer" content="webkit">
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="/seacms6.54/templets/default/images/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="/seacms6.54/templets/default/images/system.css">
<script src="/seacms6.54/templets/default/images/jquery/1.11.3/jquery.min.js"></script>
<script src="/seacms6.54/templets/default/images/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<!--[if lt IE 9]>
<script src="/seacms6.54/templets/default/images/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="/seacms6.54/templets/default/images/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<script>var sitePath='seacms6.54/'</script>
<script src="/seacms6.54/templets/default/images/system.js"></script>
<script src="/seacms6.54/js/common.js"></script>
<script src="/seacms6.54/js/function.js"></script>
<title>{seacms:searchword}-海洋CMS</title>
<meta name="keywords" content="{seacms:searchword},海洋CMS" />
<meta name="description" content="{seacms:searchword},海洋CMS" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<div class="sea-header hidden-xs">
<div class="container">
	<div class="row">
  	<div class="col-xs-3">
    	<a href="http://127.0.0.1" class="sea-logo"></a>
    </div>
  	<div class="col-xs-7">
    	<form class="form-horizontal sea-search" id="sea-search" role="search" action="" method="post">
        <div class="form-group">
        	<div class="col-sm-9">
          <input type="text" class="form-control" id="searchword" name="searchword" placeholder="Search">
          </div>
          <div class="col-sm-3 sea-col-0">    
				<button type="submit" class="btn btn-default" data-module="vod" data-action="/seacms6.54/search.php">搜视频</button>		  
        		<button type="submit" class="btn btn-default btn-success" data-module="news" data-action="/seacms6.54/so.php">搜资讯</button>
				
          </div>
        </div>
      </form>
    </div><!-- /.col-xs-5 -->
  </div><!-- /.row -->
</div>
</div>
<nav class="navbar navbar-inverse visible-lg visible-md" role="navigation">
  <div class="container">
    <ul class="nav navbar-nav navbar-left">
<li class=""><a href="http://127.0.0.1" class="dropdown-toggle" data-toggle="">首页</a></li>

        <li class="dropdown">
          <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">新闻<b class="caret"></b></a>
          <ul class="dropdown-menu">
            
			<li><a href="/seacms6.54/list/?5.html">体育</a></li>
			
			<li><a href="/seacms6.54/list/?6.html">汽车</a></li>
			
			<li><a href="/seacms6.54/list/?7.html">科技</a></li>
			
			<li><a href="/seacms6.54/list/?8.html">财经</a></li>
			
			<li><a href="/seacms6.54/list/?9.html">股市</a></li>
			
			<li><a href="/seacms6.54/list/?10.html">地方</a></li>
			
			<li><a href="/seacms6.54/list/?11.html">母婴</a></li>
			
			<li><a href="/seacms6.54/list/?12.html">生活</a></li>
			
          </ul>
        </li>

        <li class="dropdown">
          <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">娱乐<b class="caret"></b></a>
          <ul class="dropdown-menu">
            
			<li><a href="/seacms6.54/list/?13.html">明星</a></li>
			
			<li><a href="/seacms6.54/list/?14.html">音乐</a></li>
			
			<li><a href="/seacms6.54/list/?15.html">游戏</a></li>
			
			<li><a href="/seacms6.54/list/?16.html">原创</a></li>
			
          </ul>
        </li>
	


        <li class="">
          <a href="/seacms6.54/list/?3.html" class="dropdown-toggle" data-toggle="">军事</a>
        </li>

        <li class="">
          <a href="/seacms6.54/list/?4.html" class="dropdown-toggle" data-toggle="">猎奇</a>
        </li>
	
<li class=""><a href="/seacms6.54/topic/?1.html" class="dropdown-toggle" data-toggle="">专辑</a></li>
<li class=""><a href="/seacms6.54/news/" class="dropdown-toggle" data-toggle="">文章</a></li>		
<li class=""><a href="/seacms6.54/gbook.php"  class="dropdown-toggle" data-toggle="">留言求片</a></li>
<li class=""><a href="/seacms6.54/member.php" class="dropdown-toggle" data-toggle="">会员中心</a></li>
<li class=""><a href="/seacms6.54/new.html" class="dropdown-toggle" data-toggle="">最近更新</a></li>
<li class=""><a href="/seacms6.54/top/hot.html" class="dropdown-toggle" data-toggle="">热门排行</a></li>

    </ul>
  </div><!-- /.container -->
</nav><!-- /.navbar -->
<div class="container sea-nav visible-xs visible-sm">
	<div class="row">
    <ul class="list-inline">
      <li class="col-xs-3 text-left">
        <h4><a href="javascript:;" id="sea-goback"><span class="glyphicon glyphicon-chevron-left"></span></a></h4>
      </li>
      <li class="col-xs-6 text-center">
        <h4>海洋CMS</h4>
      </li>
      <li class="col-xs-3 text-right"><h4>
        <a href="http://127.0.0.1"><span class="glyphicon glyphicon-home"></span></a>
        <a href="/search.php?searchword=请输入关键词"><span class="glyphicon glyphicon-search"></span></a></h4>
      </li>
    </ul>
  </div>
</div>
<switch name="list_id" >
<case value="1"><script>seacms.cms.nav('dianying');</script></case>
<case value="2"><script>seacms.cms.nav('tv');</script></case>
<case value="3"><script>seacms.cms.nav('dongman');</script></case>
<case value="4"><script>seacms.cms.nav('zongyi');</script></case>
<case value="5"><script>seacms.cms.nav('gaoxiao');</script></case>
<default /><script>seacms.cms.nav('{$model}');</script>
</switch>
<div class="container sea-nav my-search">
<div class="row">
	<div class="col-xs-12 sea-col" style="margin-top:10px;">
  	<form id="sea-search" role="form" action="seacms6.54/search.php" method="post">
      <div class="form-group">
        <input type="text" class="form-control" id="sea-wd" name="searchword" placeholder="Search">
      </div>
    </form>
  </div>
</div>
</div>


<div class="container sea-bg vod-type">
  <div class="row">
  	<div class="col-xs-12 sea-col">
      <div class="page-header">
        <h4><span class="glyphicon glyphicon-film sea-text"></span> <a href="#">{seacms:searchword} </a> <small>共有<span class="sea-text">{seacms:searchnum}</span>个影片 第<span class="sea-text">{searchlist:page}</span>页</small></h4>
      </div>
    </div>
  </div>
</div>

<div class="clearfix sea-clearfix"></div>
<div class="container sea-bg vod-type">
<div class="row">

  <!-- -->
  <div class="clearfix"></div>
  <ul class="list-unstyled">
      {seacms:searchlist size=24 order=time}
      <li class="col-md-2 col-sm-2 col-xs-4 text-center sea-vod-img-new sea-col">
        <a href="[searchlist:link]">
        <img class="img-responsive img-thumbnail sea-img" data-original="[searchlist:pic]" alt="[searchlist:name]" src="[searchlist:pic]">
        </a>
        <h4 class="sea-text-hidden text-left">
          <a href="[searchlist:link]" title="[searchlist:name]">[searchlist:name]</a>
        </h4>
        <h6 class="sea-text-hidden text-left">
          [searchlist:actor]
        </h6>
      </li>
      {/seacms:searchlist}
    </ul>
  <!-- -->
  <div class="clearfix"></div>
  <div class="col-xs-12 sea-col text-center">
        <ul class="pagination pagination-lg hidden-xs page">
          [searchlist:pagenumber len=3]
        </ul>
        <ul class="pager visible-xs">
         {if:{searchlist:page}>1}
            <li><a href="{searchlist:backlink}">上一页</a></li>
         {else}{end if}
         {if:{searchlist:page}<{searchlist:pagecount}}
            <li><a href="{searchlist:nextlink}">下一页</a></li>
         {else}{end if}
         </ul> 
      </div>
</div>
</div>
<div class="clearfix sea-clearfix"></div>
<div class="container sea-bg sea-footer">
  <div class="row">
    <div class="col-md-10 col-sm-12 col-xs-12">
      <p>友情提示：请勿长时间观看影视，注意保护视力并预防近视，合理安排时间，享受健康生活。</p>
      <p>网站简介：努力打造海洋影视管理系统为最好的PHP影视系统!</p>
      <p>版权声明：本网站为非赢利性站点，本网站所有内容均来源于互联网相关站点自动搜索采集信息，相关链接已经注明来源。</p>
      <p>本站程序基于<a href="http://www.seacms.net" target="_blank"  style="color:#0000FF">海洋CMS</a>，<font color="#0000FF">{seacms:runinfo}</font></p>
    </div>
    <ul class="col-md-2 hidden-sm hidden-xs">
      <li>{seacms:member}</li>
      <li><a href="/seacms6.54/gbook.php" >留言反馈</a></li>
	  <li><a href="/seacms6.54/new.html" >最近更新</a></li>
	  <li><a href="/seacms6.54/hot/hot.html" >热门排行</a></li>
      <li><a href="http://www.seacms.net" target="_blank">海洋cms</a></li>
    </ul>  
  </div>
</div>
<span style="display:none"></span>
</body>
</html>